version: 2
jobs:
  build:
    working_directory: ~/app
    steps:
      - run: git config --global push.default simple
      - checkout
      - run: yarn
      - run: yarn run bootstrap
      - run: yarn test
      - run: yarn lerna-semantic-release -- pre
      - run: yarn lerna-semantic-release -- perform
      - run: yarn run changelog
    docker:
      - image: node:7
  
